apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodeapp-chat-bot
  labels:
    app: nodeapp-chat-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp-chat-bot
  template:
    metadata:
      labels:
        app: nodeapp-chat-bot 
    spec:
      containers:
      - name: nodeserver
        image: thilina9718/nodeapp-chat-bot:latest
        ports:
        - containerPort: 3000
