apiVersion: v1
kind: Service
metadata:
  name: service-nodeapp-chat-bot
spec:
  selector:
    app: nodeapp-chat-bot
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000

    
